---
- name: Fix broken cloud-init
  include: cloud-init.yml
  when: ansible_distribution_major_version == "6"

- name: Stop iptables
  service:
    name: iptables
    state: stopped
  when: ansible_distribution_major_version == "6"

- name: Stop firewalld
  service:
    name: firewalld
    state: stopped
  when: ansible_distribution_major_version == "7"

- include: ../nfs.yml
  tags:
    - nfs
  when: ansible_distribution_major_version == "7"

- include: imitate_ubuntu.yml
